// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Galaxy.Angular.API.Infrastructure.Data.EntityFrameCore.Entities
{
    public partial class Product
    {
        public Product()
        {
            OrderItems = new HashSet<OrderItem>();
        }

        public int ProductId { get; set; }
        public string ProductName { get; set; }
        public decimal? ItemCost { get; set; }

        public virtual ICollection<OrderItem> OrderItems { get; set; }
    }
}